// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/decks": {
    params: {};
  };
  "/decks/:deckId": {
    params: {
      "deckId": string;
    };
  };
  "/decks/:deckId/cards": {
    params: {
      "deckId": string;
    };
  };
  "/decks/:deckId/cards-slide/:flashcardIndex": {
    params: {
      "deckId": string;
      "flashcardIndex": string;
    };
  };
  "/decks/:deckId/edit/cards": {
    params: {
      "deckId": string;
    };
  };
  "/decks/:deckId/edit/cards-slide/:flashcardIndex": {
    params: {
      "deckId": string;
      "flashcardIndex": string;
    };
  };
  "/profile": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/decks" | "/decks/:deckId" | "/decks/:deckId/cards" | "/decks/:deckId/cards-slide/:flashcardIndex" | "/decks/:deckId/edit/cards" | "/decks/:deckId/edit/cards-slide/:flashcardIndex" | "/profile";
  };
  "routes/layouts/RootLayout.tsx": {
    id: "routes/layouts/RootLayout";
    page: "/" | "/decks" | "/decks/:deckId" | "/decks/:deckId/cards" | "/decks/:deckId/cards-slide/:flashcardIndex" | "/decks/:deckId/edit/cards" | "/decks/:deckId/edit/cards-slide/:flashcardIndex" | "/profile";
  };
  "routes/views/index.tsx": {
    id: "routes/views/index";
    page: "/";
  };
  "routes/views/decks/index.tsx": {
    id: "routes/views/decks/index";
    page: "/decks";
  };
  "routes/layouts/DeckLayout.tsx": {
    id: "routes/layouts/DeckLayout";
    page: "/decks/:deckId" | "/decks/:deckId/cards" | "/decks/:deckId/cards-slide/:flashcardIndex" | "/decks/:deckId/edit/cards" | "/decks/:deckId/edit/cards-slide/:flashcardIndex";
  };
  "routes/views/decks/deck/cards.tsx": {
    id: "routes/views/decks/deck/cards";
    page: "/decks/:deckId/cards";
  };
  "routes/views/decks/deck/cards-slide.tsx": {
    id: "routes/views/decks/deck/cards-slide";
    page: "/decks/:deckId/cards-slide/:flashcardIndex";
  };
  "routes/views/decks/deck/edit/cards.tsx": {
    id: "routes/views/decks/deck/edit/cards";
    page: "/decks/:deckId/edit/cards";
  };
  "routes/views/decks/deck/edit/cards-slide.tsx": {
    id: "routes/views/decks/deck/edit/cards-slide";
    page: "/decks/:deckId/edit/cards-slide/:flashcardIndex";
  };
  "routes/views/profile.tsx": {
    id: "routes/views/profile";
    page: "/profile";
  };
};